# Generated by Django 4.2.6 on 2023-11-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0002_order_product_usercourier_userclient_useradmin_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
