# Generated by Django 4.2.6 on 2023-11-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Activewear', 'Activewear'), ('Outerwear', 'Outerwear'), ('Formal Wear', 'Formal Wear'), ('Casual Wear', 'Casual Wear'), ('Underwear', 'Underwear'), ('Swimwear', 'Swimwear'), ('Vintage Clothing', 'Vintage Clothing'), ('Maternity Wear', 'Maternity Wear'), ('Sportswear', 'Sportswear'), ('Sleepwear', 'Sleepwear'), ('Workwear', 'Workwear'), ('Ethical and Sustainable Fashion', 'Ethical and Sustainable Fashion'), ('Costumes and Cosplay', 'Costumes and Cosplay'), ('Designer Clothing', 'Designer Clothing')], max_length=50),
        ),
    ]
