# Generated by Django 4.2.6 on 2023-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproduct',
            name='photolink',
            field=models.ImageField(upload_to='products_photo/'),
        ),
    ]
