# Generated by Django 4.2.6 on 2023-11-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0007_remove_userclient_user_alter_order_userclient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='userclient',
            new_name='user',
        ),
    ]
