# Generated by Django 4.2.6 on 2023-11-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0008_rename_userclient_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userclient',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='userclient',
            new_name='user',
        ),
    ]
