# Generated by Django 4.2.6 on 2023-11-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0010_order_full_name_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
