# Generated by Django 5.0 on 2023-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0012_alter_order_date_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='size_name',
            field=models.CharField(default=40, max_length=12),
            preserve_default=False,
        ),
    ]
